// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test1', async function() {
    // Test name: Test1
    // Step # | name | target | value
    // 1 | open | https://umassdgithub.github.io/calculator/ | 
    await driver.get("https://umassdgithub.github.io/calculator/")
    // 2 | setWindowSize | 1753x1082 | 
    await driver.manage().window().setRect({ width: 1753, height: 1082 })
    // 3 | click | id=num1 | 
    await driver.findElement(By.id("num1")).click()
    // 4 | type | id=num1 | 5
    await driver.findElement(By.id("num1")).sendKeys("5")
    // 5 | click | id=num2 | 
    await driver.findElement(By.id("num2")).click()
    // 6 | type | id=num2 | 7
    await driver.findElement(By.id("num2")).sendKeys("7")
    // 7 | select | id=operation | label=Add (+)
    {
      const dropdown = await driver.findElement(By.id("operation"))
      await dropdown.findElement(By.xpath("//option[. = 'Add (+)']")).click()
    }
    // 8 | click | css=option:nth-child(2) | 
    await driver.findElement(By.css("option:nth-child(2)")).click()
    // 9 | click | css=button | 
    await driver.findElement(By.css("button")).click()
    // 10 | assertText | id=result | Result: 12
    assert(await driver.findElement(By.id("result")).getText() == "Result: 12")
  })
  it('Test2', async function() {
    // Test name: Test2
    // Step # | name | target | value
    // 1 | open | https://umassdgithub.github.io/calculator/ | 
    await driver.get("https://umassdgithub.github.io/calculator/")
    // 2 | setWindowSize | 1357x1010 | 
    await driver.manage().window().setRect({ width: 1357, height: 1010 })
    // 3 | click | id=num1 | 
    await driver.findElement(By.id("num1")).click()
    // 4 | type | id=num1 | 8
    await driver.findElement(By.id("num1")).sendKeys("8")
    // 5 | click | id=num2 | 
    await driver.findElement(By.id("num2")).click()
    // 6 | type | id=num2 | 9
    await driver.findElement(By.id("num2")).sendKeys("9")
    // 7 | click | css=html | 
    await driver.findElement(By.css("html")).click()
    // 8 | select | id=operation | label=Subtract (-)
    {
      const dropdown = await driver.findElement(By.id("operation"))
      await dropdown.findElement(By.xpath("//option[. = 'Subtract (-)']")).click()
    }
    // 9 | click | css=option:nth-child(3) | 
    await driver.findElement(By.css("option:nth-child(3)")).click()
    // 10 | click | css=button | 
    await driver.findElement(By.css("button")).click()
    // 11 | assertText | id=result | Result: -1
    assert(await driver.findElement(By.id("result")).getText() == "Result: -1")
  })
})
